.github/workflows/build-dev.yml
.pre-commit-config.yaml
bc/channel/management/commands/post.py
bc/subscription/api_views.py
docker/django/Makefile
docker/django/README.md

This fixes #33 by:
- Adding a few more features to the make file (all copied from CL)
- Adding a readme
- Adding a CI to auto-build and push images to docker (copied from CL)
This should make our lives easier, since it'll mean there are always multi-architecture images ready in docker.
I also pushed our first prod images so they'd be available to k8s: https://hub.docker.com/repository/docker/freelawproject/bigcases2/tags

33 auto build dev images

---

docker/bigcasesbot/docker-compose.yml

This PR changes the value of the POSTGRES_DB environment variable to define the name for the default database that is created when the Postgres service is started.
I noticed that after merging https://github.com/freelawproject/bigcases2/pull/50 the django app was failing to start and then I realized the default name of the DB changed.
I think this PR will make developers' life easier.

fix(docker compose): Change the POSTGRES_DB variable

---

bc/subscription/api_permissions.py

This PR fixes the endpoint that handles the CL webhooks.
After reviewing the webhook logs, I realize the class that checks the IP address of incoming requests is returning a falsy value when the request is coming from one of the trusted IP and that's the reason the API is throwing error 403 with a message saying that **the Authentication credentials were not provided**.

fix(subscription): Add return value to the has_permission method.

---

.github/workflows/tests.yml
bc/core/tests.py
bc/core/utils/messages.py
bc/subscription/api_views.py
bc/subscription/tasks.py

This PR adds support to allow numberless entries and adds a new template to create posts in Mastodon using the Webhook events. This PR fixes https://github.com/freelawproject/bigcases2/issues/79.

fix(subscriptions):  Allow numberless entries and add minute template

---

bc/core/utils/messages.py

This PR adds the docket link to the `MINUTE_TEMPLATE`.

feat(core): Add docket link in the template for minute entries

---

bc/core/utils/messages.py

This is a second pass at the work in https://github.com/freelawproject/bigcases2/pull/94. 
Looking at this post: https://law.builders/@bigcases/109938980184504362
I think it should be shorter before going to the "See more" so this does that. I think if we're going to provide a picture, then we shouldn't provide so much text.

Make too-long posts shorter

---

bc/core/utils/messages.py

This PR fixes https://github.com/freelawproject/bigcases2/issues/92 by adding "None" to the `DO_NOT_POST` regex expression, so the bot won't create posts with bad data.

feat(core): Update DO_NOT_POST regex expression

---

bc/assets/templates/includes/footer.html
bc/assets/templates/includes/header.html
bc/assets/templates/includes/under_construction.html
bc/web/static_src/src/styles.css
bc/web/templates/homepage.html

This PR fixes accessibility issues from PageSpeed Insights.
- Adds [alt] attributes to the image elements
- Use darker text in the footer
- Use the fallback font to display the text during webfont load

fix(web): Tweak homepage accessibility

---

bc/core/utils/messages.py

This tweaks the mastodon template a bit to make it a bit clearer. There are a lot of cases that are named "In re...". When we got those, we'd tweet something like, `New filing in In re...`, which is confusing. 
This tweaks it to be `New filing: "In re...."`, which should be better and I think is no longer.

feat(masto): Tweak post template

---

bc/web/urls.py

This PR fixes the path to the `sponsor.html` and `about.html` files. 
The current implementation of the project is falling to load these pages because is trying to get the templates from a folder called `big_cases` but these files are inside a folder called `big-cases`.

fix(web): Update path to the sponsors and about templates

---

bc/assets/templates/includes/footer.html

This PR tweaks the footer template following the suggestions from https://github.com/freelawproject/bigcases2/issues/119 and also updates the styles to be consistent with the design.

feat(templates): Remove links and sections from the footer

---

bc/subscription/management/commands/lookup.py
bc/subscription/models.py
bc/subscription/services.py
bc/subscription/tasks.py

This PR fixes https://github.com/freelawproject/bigcases2/issues/95
- Prompt for a case summary in the `lookup --add`
- Adds a new property to the `subscription` model that adds the **summary**(when its available) to the **docket name**.
- Use the new property in the mastodon templates.

feat(subscription): Prompt for case summary in the lookup command

---

bc/assets/templates/includes/header.html
bc/assets/templates/includes/submit-button.html
bc/channel/admin.py
bc/core/utils/network.py
bc/settings/django.py
bc/subscription/api_permissions.py
bc/subscription/models.py
bc/urls.py
bc/users/templates/register/login.html
bc/users/urls.py
bc/web/templates/includes/suggestion-form.html
bc/web/templates/includes/waitlist-form.html
poetry.lock
pyproject.toml

This PR removes the Sign In link on the header, adds django-ratelimit as a dependency, and redirects the admin login to a custom login page that uses a ratelimiting decorator. 
Here's a screenshot of the login page:

feat(web): Remove Sign In link and set up admin login

---

bc/assets/static-global/js/dropdown.js
bc/assets/templates/includes/header.html
bc/assets/templates/includes/inlines/x-mark.svg
bc/web/templates/big-cases/about.html

This PR adds the mobile menu to the website and fixes https://github.com/freelawproject/bigcases2/issues/142. 
This PR also adds the "What next?" section to bottom of the about page. 
Here's a gif of the mobile menu: 
This is the "What next" section in the about page:

feat(web): Add the mobile menu

---

bc/core/utils/status/templates.py
bc/subscription/management/commands/lookup.py

This PR tweaks the `lookup` command to create a new status in each enabled channel after subscribing to a new case. This PR fixes https://github.com/freelawproject/bigcases2/issues/112.
Here are screenshots of the posts created after subscribing:

feat(subscription): Add a post after subscribing to a new case.

---

bc/assets/templates/includes/footer-link.html
bc/assets/templates/includes/footer.html
bc/assets/templates/includes/header.html

This PR adds the `aria-label` attribute to the HTML templates. This attribute fixes the following issues from the [PageSpeed report](https://pagespeed.web.dev/analysis/https-bots-law/34i2g5b1w1?form_factor=mobile):
- Buttons do not have an accessible name
- Links do not have a discernible name

feat(templates): Add the aria-label attribute to links and buttons

---

bc/subscription/models.py

This PR removes the parameter `redirect_to_download` from the PDF link and uses the new parameter called `redirect_or_modal` instead.
Here's one tweet that uses the new link:
https://twitter.com/flp_tests/status/1641238923274797058

feat(subscription): Update the pdf link to add the new parameter

---

bc/sponsorship/services.py
bc/sponsorship/signals.py
bc/sponsorship/utils.py
bc/subscription/api_views.py
bc/subscription/exceptions.py
bc/subscription/tasks.py
bc/subscription/urls.py
bc/subscription/utils/courtlistener.py

This PR adds logic to automatically purchase documents from PACER and fixes https://github.com/freelawproject/bigcases2/issues/16.
- Add the page_count attribute to the lookup_document request
This PR tweaks the helper method called `lookup_document_by_doc_id` to add the `page_count` attribute in the response of the CL API and also updates the type hinting of the helper method. We need the `page_count` of the document to compute its price. 
- Adds a helper method to purchase documents using the CL API.
This helper uses the `recap-fetch/` endpoint and the PACER's login credentials to purchase PDFs.
- Adds a helper method to download documents from the RECAP archive.
- Tweaks the helper method called `process_filing_webhook_event` to add the logic …

feat(subscription): Purchase documents from PACER

---

bc/assets/templates/includes/footer.html
bc/assets/templates/includes/header.html
bc/web/templates/homepage.html

This PR adds the `height` and `width` properties to the image elements in the HTML templates. These properties fix the following issue from the [PageSpeed report](https://pagespeed.web.dev/analysis/https-bots-law/gzo5arnl2a):
- Image elements do not have explicit width and height.

feat(templates): Add explicit width and height to img elements

---

bc/core/utils/images.py

This PR tweaks the method called `get_max_character_count` in the `TextImage` class and fixes the overflow in images like the one attached to this tweet:
https://twitter.com/big_cases/status/1644518874774388737
In the previous tweet, We see that the text in the first image overflows the rectangle. This issue happened because We use a `while` loop to increase the maximum number of characters that should be rendered per line but the current implementation of the logic inside the loop updates the value of the `max_character` variable without checking if the new value allows us to render the text without overflowing the image
This commit adds an if statement to check the new value for the `max_character` variable before updating it.
Here's a post using new logic and the same case that has the …

fix(core): Check the max number of characters before updating its value.

---

bc/users/admin.py

This PR enhances the django admin interface for the `User` model by extending the `django.contrib.auth.admin.UserAdmin` class.
Django uses the `UserAdmin` class to render a nice-looking admin site for the `User` model. By just using this class in our `admin.py` file, we can get the same look for our model.  
The `UserAdmin` provides a custom **form** to create users from the admin panel(uses the [user/add_form.html ](https://github.com/django/django/blob/8b1ff0da4b162e87edebd94e61f2cd153e9e159d/django/contrib/admin/templates/admin/auth/user/add_form.html) file to render the form after clicking the `add user` button in the admin site) and We can customize the **fields** included in the form (like this PR does in line 12 of the admin.py file). This class will also take care of password …

feat(user): Enhance admin site for the User model

---

bc/core/utils/status/templates.py
bc/sponsorship/admin.py
bc/subscription/tasks.py

This PR adds a regex expression to filter documents the Bot should purchase and also tweaks the admin site for the `Transaction` model

feat(core): Add a regex expression to filter documents to purchase

---

bc/core/utils/status/templates.py
bc/subscription/tasks.py

This PR adds a hashtag to the mastodon templates and fixes https://github.com/freelawproject/bigcases2/issues/196.
Here are screenshots of posts created with the new template:

feat(core): Add hashtags to the mastodon templates

---

bc/assets/static-global/js/fix-toolbar-for-htmx.js
bc/assets/templates/base.html
bc/subscription/templates/add-case.html
bc/web/static_src/src/styles.css

This PR fixes the errors with the CSP policies of the website caused by the inline elements in the `add-case` template.
- Adds a meta tag to tweak the configuration options of HTMX and avoid injecting inline styles. I used the comments from [CSP issue: style-insertion]( https://github.com/bigskysoftware/htmx/issues/862) to find the option that We should change. 
- Move the js code suggested on the `debug toolbar` docs into an asset to avoid inline scripts in the `add-case.html` template.

fix(template): Remove inline elements from the add case template

---

.github/workflows/tests.yml
bc/assets/static-global/js/checkbox-group.js
bc/channel/management/commands/post.py
bc/channel/selectors.py
bc/channel/tasks.py
bc/channel/tests/factories.py
bc/channel/tests/test_selectors.py
bc/channel/utils/connectors/base.py
bc/core/utils/commands.py
bc/core/utils/tests/base.py
bc/subscription/api_views.py
bc/subscription/management/commands/lookup.py
bc/subscription/management/commands/subscribe.py
bc/subscription/selectors.py
bc/subscription/tasks.py
bc/subscription/templates/add-case.html
bc/subscription/templates/includes/search_htmx/case-form.html
bc/subscription/templates/includes/search_htmx/search-form.html
bc/subscription/tests/factories.py
bc/subscription/tests/test_selectors.py
bc/subscription/tests/test_utils.py
bc/subscription/views.py
bc/users/tests/factories.py
bc/web/views.py
poetry.lock
pyproject.toml

This PR tweaks queries related to subscription and channels to use the relationships added in #235 and also update the page about the Big Cases Bot and the form to follow new cases.
- Adds a selector called `get_subscriptions_for_big_casesto` to filter the list of subscriptions and show only those linked to channels related to the Big Cases bot and not for the other new bots.
- Add helpers to show the list of channels as a table in the `post` and the `lookup` command
- Refactor the `post` command.
- Tweaks the `lookup` command to show a list of channels and add them to the new subscriptions. 
- Add a new selector function to get channels linked to a user
- Updates the form to add channels from the website to show the list of channels using …

feat(web): Tweak logic related to subscriptions. 

---

bc/subscription/tasks.py

This PR fixes the `enqueue_posts_for_docket_alert` helper after the updates We introduced in #236 
The current implementation of this helper is passing `pk` getter property of the `FilingWebhookEvent` class (in line 81) to the `enqueue` method, but We should've used the `webhook_event` argument instead (like in line 76). The Bot is not creating new statuses because the enqueue method is raising an exception when it tries to de-serialize the Python object we're passing as the pk. 
This PR updates the arguments used in the `enqueue` method to remove the class and use the `webhook_event` argument instead.

fix(subscription): Use the pk property of webhook_event argument

---

bc/subscription/models.py

This PR adds the `order_by` query parameter to the docket links and fixes #252.
This PR updates the property called `cl_url` in the `Subscription` model. The current implementation of this property computes links that redirect the users to the **docket page** in CL but We can't add query parameters to this URL because **Django** removes it while redirecting the request, so We're tweaking the property to return the direct link to the docket page and also adding the order_by parameter.

feat(subscription): Tweak the links to the CL dockets

---

bc/subscription/api_views.py

This PR implements the first strategy described in #188.
The PR tweaks the logic in the `handle_docket_alert_webhook` view to create a status immediately after the Bot receives a webhook containing info about the PDF.

feat(subscription): Create Post immediately for webhook with docs

---

bc/channel/apps.py
bc/channel/signals.py

This PR adds logic to Invalidate the cache after adding a new channel group to the DB. This PR fixes https://github.com/freelawproject/bigcases2/issues/263

feat(channel): Invalidate cache after adding a new bot.

---

docker/django/Dockerfile

After merging #265, I realized the [Build and deploy](https://github.com/freelawproject/bigcases2/actions/runs/5292810658/jobs/9580217372)  step failed and showed the following error:
```
It looks like node.js and/or npm is not installed or cannot be found.
Visit https://nodejs.org/ to download and install node.js for your system.
If you have npm installed and still getting this error message, set the NPM_BIN_PATH variable in settings.py to 
match path of NPM executable in your system.
```
I tried setting the `NPM_BIN_PATH` variable but it didn't work. I found that using a newer version of Nodejs fixes the issue, so this PR updates the version installed from nodesource to fix this bug.

chore(dockerfile): Update node version in docker images

---

.github/workflows/lint.yml
.github/workflows/tests.yml
bc/subscription/templates/includes/search_htmx/time-out.html
bc/subscription/views.py

This PR adds a template to display a human-friendly message for timeout exceptions and fixes #242. 
Here's a screenshot of the new message:
This PR also adds a new step to the **linting** and **testing** action to create better keys to uniquely identify each version of our cache.

feat(subscription): Adds a human-friendly message for timeout exceptions

---

bc/settings/project/security.py

The `@tailwindcss/forms` plugin, uses data URIs for form elements in CSS. Allow these by adding `data:` to the allowed image sources of the content security policy.
Fixes: #297

fix(security): adjust CSP policy to accomodate Tailwindcss

---

bc/assets/templates/includes/header.html

`z-index` determines ordering relative to an element's closest `relative` ancestor. The z-order of the dropdown is relative to z-order of its `absolute`-ly positioned parent.
This parent and the container of the input share a `relative` container (`<body>`) and, having no explicit index, are ordered by lexically. The input container comes later, and so it is ordered above the dropdown container. A child element cannot transcend its parent's z-order, and so the input rendered above the container. Fix by placing the `z-index` on the `absolute` container.
Fixes: #314

fix(web): z-ordering of dropdown

---

bc/settings/project/security.py

Courtlistener recieved more recent attention to its CSP directives. Now that the policy has been dialed- in there, bring these changes to Big Cases.
- Consistently format `*_SRC` lists
- Consistently specify protocol for sources (see `AWS_S3`)
- Specify `upgrade-insecure-requests`
- Specify `object-src`: The HTML `object` tag isn't used; restrict it.
- Specify `style-src`: Allow `default-src` to be more restrictive.
- Specify `base-uri`: The HTML `base` tag isn't used; restrict it.
- Include `haptcha.com` subdomains: follows documented requirements.

chore(security): tighten-up CSP configuration

---

docker/bigcasesbot/docker-compose.yml

`bc2-redis`'s use of `6379` conflicts with `cl-redis` (CourtListener) and frustrates parallel development. There's no need for the `bc2-redis` and `bc2-postgresql` container ports to be exposed on the host. It is enough that they are accessible within the `bc2_net_overlay` Docker network.

chore(docker): drop ports from ancillary containers

---

.github/workflows/bulid-and-deploy.yml
.github/workflows/lint.yml
.github/workflows/tests.yml

When run, the lint and build workflows emit the warning: our workflows:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
The disabling (initially set for 31st May 2023) has been postponed indefinitely. Nevertheless, the deprecated command should be replaced. Here a minor adjustment will suffice - do it.

chore(workflows): update steps to use new environmental files

---

bc/subscription/views.py

After checking the issue reported in Slack about **J6 cases**, I noticed the **Bot** didn't create an alert for the case in CL. As a result, the bot didn't get the webhooks about its new entries. 
This PR fixes this bug by adding logic to enqueue a job that creates the alerts in CL after users submit the follow-a-case form. 
I already checked all the existing subscriptions and fixed those that didn't create the alert.

fix(subscription): Create alert in CourtListener after adding a case

---

bc/channel/selectors.py
bc/sponsorship/services.py
bc/sponsorship/tests/test_services.py

This PR fixes #369.
In line [27](https://github.com/freelawproject/bigcases2/blob/e5a90abf668beeb21d773c9a73e5c12f0aedb7e9/bc/sponsorship/services.py#L27), the code raised an exception and it appears that the list comprehension was unable to obtain the sponsorship PK.
In #369, the transaction we tried to log is related to a document that belongs to a case followed by two sponsored group( big cases and tech cases) but the sponsorship from big cases is not available (we spent all that money :( ). The code should've skipped the big cases group but it tried to get the active sponsorship of that group and that raised the exception. 
I thought that was odd because we're using a filter(`if group.sponsorships`) to check whether the group has a sponsorship or not before trying to get the `pk` and …

fix(sponsorship): Tweak logic to filter sponsored groups

---

docker/django/Dockerfile

_Analogue of freelawproject/courtlistener#3110_
The Docker image, `python:3.11-slim`, that images are built from, recently stopped working with the installation script that is downloaded and executed for the Poetry tool:
```
RUN curl -sSL https://install.python-poetry.org/ | python3 -
```
Instead of this script, use the installation with `pip` that is a alternative approach which doesn't have this problem and is more direct than the script.
Also in this branch:
- Removal of surplus `POETRY_HOME` argument
- Remove nonoperative `VENV_PATH` environment variable

fix(build): use manual installation for python Poetry 

---

docker/django/Dockerfile

_Analogue for freelawproject/courtlistener#3107_
It is a best practice for production processes to not run at `root` (also for `root` to be inaccessible via `sudo`). Docker's best practices emphasize this:
> If a service can run without privileges, use `USER`
> to change to a non-root user.
Typically, binding to port `80` requires special
privileges and presents a problem, but both `web-dev` and `web-prod` bind on `:8xxx`. Uniformly use
`www-data` user for all Docker images/containers.

chore(build): use www-data user for all services

---

docker/django/Dockerfile

Reverts freelawproject/bigcases2#379
`django-tailwind` does not play well with this change. Addressing this will take some extra attention – revert for now.

Revert "chore(build): use www-data user for all services"

---

docker/django/Dockerfile

_Analogue to freelawproject/courtlistener#3130_
Building production from a downloaded archive rather than the Docker build context was done to guard against the risk that an unclean working copy could cause WIP code to be deployed.
Today, responsibility for building and deployment are entirely handled by CD process (Github Actions). This is the best practice and has made the archive download safeguard unnecessary.
Change the `build-prod` target to use the Docker buildcontext rather than a downloaded copy of the repository. Once done, the only remaining difference between the two targets is the --without dev option. Eliminate this difference by using `$BUILD_ENV` for the `RUN` instruction and merging the, otherwise identical, stages.

chore(build): drop use of github archive and merge build-* stages

---

bc/subscription/admin.py
bc/subscription/api_views.py

This PR adds logic to handle the `MultipleObjectsReturned` exception and also adds the `FilingWebhookEvent` model to the admin interface so we can remove duplicate entries.
Here's a screenshot of the new list in the admin panel:

fix(subscription): Add logic to handle the MultipleObjectsReturned exception

---

bc/core/utils/string_utils.py

This PR refines the helper function that truncates long descriptions for posts. 
While debugging the latest events related to this [sentry issue](https://freelawproject.sentry.io/issues/4088080862). I discovered that the API was throwing an error regarding the post length. Upon revisiting the [Twitter specification for character count](https://developer.twitter.com/en/docs/counting-characters), I realized that the API counts emoji as two characters. However, our current `trunc` method was not accounting for this, leading to potential truncation issues.

feat(utils): Add logic to count emojis according to the Twitter spec

---

bc/channel/utils/connectors/bluesky.py
bc/channel/utils/connectors/bluesky_api/client.py

This PR tweaks the post_media method to handle big thumbnails by logging the error and returning `None` instead of raising an exception. This new approach allows us to exclude those big thumbnails from the embed array and continue the post-creation process.
Fixes #436

feat(channels): Refine media upload for Bluesky posts

---

bc/core/tests/test_mastodon_template.py
bc/core/utils/status/base.py

This PR tweaks the implementation of the `_check_output_validity` method in the `BaseTemplate` class. 
The current implementation of the method in the `BaseTemplate` class is using `len` to count the characters in the output but this approach is inaccurate for Mastodon and Twitter templates because adds the full length of the links to the count. This is not an issue for the Bluesky template class because we implemented a custom method. This issue with the character count led to misleading error messages in the `add-a-case` form and prevented users from following new cases.
This PR adds logic to remove links from the output and fixes the character count. Additionally, it adds a test to prevent regressions.

fix(template): Tweak method to check output validity in the base class

---

bc/settings/django.py
bc/settings/project/security.py
poetry.lock
pyproject.toml

This PR fixes #445  by adding the [django-permissions-policy](https://github.com/adamchainz/django-permissions-policy) package and disabling the browsing-topics feature.

445-block the browsing topics feature

---

bc/channel/utils/connectors/bluesky_api/types.py

Updates `Session` class to handle 'emailAuthFactor' in the `createSession` response (related to https://github.com/bluesky-social/atproto/pull/2419).

feat(bluesky): Updates the Session dataclass

---

bc/channel/utils/connectors/bluesky_api/client.py
bc/channel/utils/connectors/bluesky_api/types.py

Fixes https://github.com/freelawproject/bigcases2/issues/514
A little rusty with Python, and wasn't sure how I'd get the Bluesky bot to work, thought I'd chip in just a little.

Parse hashtags for Bluesky

---

bc/channel/utils/connectors/bluesky_api/client.py

This PR tweaks the `_parse_tags` method to use `UTF-8` encoding for improved consistency in handling text content.

feat(bluesky): Tweaks the method to parse hashtags

---

bc/assets/templates/includes/header.html

This PR updates the `header.html` template to use `POST` requests instead of `GET` to the [built-in logout view](https://docs.djangoproject.com/en/4.1/topics/auth/default/#django.contrib.auth.views.LogoutView).

fix(header): Update the template to use a POST request for the LogoutView

---

bc/channel/utils/connectors/bluesky_api/client.py

This PR introduces logic to handle `ReadTimeout` exceptions that may occur during social card creation. When such an exception is encountered, the code will prioritize successfully creating the post itself, ensuring the core functionality remains uninterrupted.
Here's a screenshot of a post with no social card:

feat(bluesky): Handle ReadTimeout exceptions during social card creation

---

.github/workflows/bulid-and-deploy.yml

New step will apply any update to the Bots.law environment variables before running a restart or creating a new pod.
Secret which holds the vars will be updated and then the step will wait for the secret to have a synced status.
Wait has a limit of 30 seconds which if it's reach, the command will exit with an error status.

feat(deploy): Sync env vars before deployment

---

bc/subscription/tasks.py
bc/subscription/tests/test_tasks.py

This pull request addresses the memory-related issues identified in #577 by significantly enhancing the task enqueueing code. 
Key improvements:
- Refactored helper methods: The helper method responsible for enqueuing tasks has been updated to send only document URLs instead of entire byte objects. This substantially reduces memory usage, particularly for large documents.
- The task code has been updated to handle document URLs effectively.

feat(subscription): Optimize document handling in subscription tasks

---

bc/users/tests/test_views.py
bc/users/views.py

This PR fixes #601  by adding stricter validation to the email query parameter to mitigate text injection risks. If an invalid email format is detected, a SuspiciousOperation exception is raised and logged at the Error level.

fix(users): Prevent text Injection in Email Query Parameter

---

bc/channel/utils/connectors/bluesky_api/client.py

This commit refines the regex pattern to specifically match and remove markup notation associated with embedded links. This ensures that the rest of the post content remains intact, preventing unintended formatting changes.
By making these modifications, we've improved the accuracy and reliability of the text cleaning process, ensuring that embedded links are displayed correctly within Bluesky posts.
Here's a screenshot of one of the post created with this new clean method:

fix(bluesky): Refines _clean_text method

---

bc/settings/third_party/aws.py

The [PR that implements Threads support](https://github.com/freelawproject/bigcases2/pull/618) added a new env variable to support AWS temporary credentials, which requires a session token, but the variable was only set for development so when running in production we get this:
```
cannot import name 'AWS_SESSION_TOKEN' from 'bc.settings' (/opt/bigcases2/bc/settings/__init__.py)
```
This PR solves this issue.

fix(aws_settings): Add missing variable to production settings

---

bc/channel/models.py
bc/channel/signals.py
bc/channel/tasks.py
bc/channel/utils/connectors/base.py
bc/channel/utils/connectors/threads.py
bc/channel/utils/connectors/threads_api/client.py
bc/subscription/tasks.py
scripts/get-threads-keys.py

Resolves #627 
Long-lived tokens need to be at least 24 hours old to be refreshed so upon creation of a new Threads channel, a `post_save` signal enqueues a job to refresh the token in 2 days. After that, we enqueue a new job in as many seconds as the `expires_in` value from the token refresh response.

feat(Threads): Refresh Threads access tokens automatically.

---

bc/assets/templates/includes/header.html

Closes #640 
This is a temporary fix to hide the banner, but it should be the last time we need to change the code to toggle this since we're adding a setting for it [here](https://github.com/freelawproject/bigcases2/issues/641)

feat(header): comment out GivingTuesday banner

---

bc/core/apps.py
bc/core/signals.py

This PR addresses #646 by using the post-save signal to invalidate the cache whenever a BannerConfig object is saved or updated.

feat(core): Invalidate cache after saving banners

---

pyproject.toml

We're only using Poetry for dependency management and not for packaging the project, but Poetry has always attempted and failed to package it with a warning ([see an example here](https://github.com/freelawproject/bigcases2/actions/runs/12568106838/job/35035311609#step:7:131)). Newer versions of Poetry now throw an error instead of a warning, so a few days ago pipelines started failing. This PR fixes that by preventing Poetry from attempting to package the project.

build(poetry): set poetry packaging-mode to false

---

docker/bigcasesbot/docker-compose.yml

Copy of https://github.com/freelawproject/courtlistener/pull/5513 for this repository.

fix(docker): Remove outdated compose version numbers

---

bc/core/tests/test_templates.py
bc/core/utils/status/templates.py

Fix for #617. Apostrophes and other punctuation for Django templates were getting mangled because Django autoescapes HTML characters. This PR fixes the issue by enclosing the Big Cases Bot templates that are Django templates—the Follow-New-Case templates—within the Django `autoescape` tag. The tests added failed without the code change, and passed after the code change.

Do not escape variables in follow-new-case templates

---

ARCHITECTURE.md
bc/channel/management/commands/post.py

This PR removes commands that are no longer needed from the `ARCHITECTURE.md` file, reducing potential confusion for new contributors.
It also adds a validation to the `post` command, ensuring channels exist in the database.

chore: Clean up architecture file
