freelawproject/bigcases2

.env.example, bc/settings/__init__.py, bc/settings/django.py, bc/settings/project/security.py, bc/settings/project/testing.py, bc/settings/third_party/courtlistener.py, bc/settings/third_party/sentry.py, poetry.lock, pyproject.toml
This fixes #47 by adding a number of new settings and by adding the django-csp package.
=> 47 settings and security

.github/workflows/bulid-and-deploy.yml
We won't know how well this works until it's merged, but it's copied from CourtListener's with one change. The one change is that it doesn't do collectstatic. Otherwise, it's pretty much the same, and I think I've got the right permissions set up for it to gooooo
=> feat(ci): Add auto-deploy!

bc/assets/templates/base.html, poetry.lock, pyproject.toml
If curious, see: https://docs.joinmastodon.org/user/profile/#verification
=> Add rel="me" on bots.law

scripts/get_mastodon_keys.py
This PR adds an if statement that checks the value of the `MASTODON_SERVER` and `MASTODON_TOKEN` variables before generating the keys that are used in the subscription.
=> feat(scripts): Add Exception to let the user know if a variable is missing

bc/subscription/management/commands/lookup.py
This PR fixes https://github.com/freelawproject/bigcases2/issues/88 by adding a new argument called `name` to the `lookup` command
=> feat(subscription): Add new argument to the lookup command

.env.example, .github/workflows/bulid-and-deploy.yml, bc/core/utils/storage.py, bc/settings/__init__.py, bc/settings/django.py, bc/settings/project/security.py, bc/settings/third_party/aws.py, poetry.lock, pyproject.toml
This PR adds settings to use **S3** and **CloudFront** to serve static files.
=> feat(setting): Tweak static file settings

.github/workflows/bulid-and-deploy.yml
This PR fixes the github action that collects static assets.
=> fix(github action): Change arguments for the tailwind command

bc/settings/project/security.py
This PR adds the `connect-src` directive to the settings module.
=> feat(setting): Add the CSP connect-src directive.

bc/assets/templates/base.html
This PR adds the `viewport` and the `language` meta tag. This PR fixes the issue with the responsive design for mobile screen sizes
=> fix(template): Add meta tags to fix the responsive design

bc/assets/templates/base.html
This PR adds the description meta `tag` to the `base.html` template.
=> feat(template): Add the meta description to the base template.

bc/assets/templates/includes/footer.html, bc/assets/templates/includes/header.html, bc/web/templates/big-cases/about.html, bc/web/templates/big-cases/my-code.html, bc/web/templates/big-cases/sponsors.html, bc/web/templates/collaboration.html, bc/web/templates/homepage.html, bc/web/templates/includes/suggestion-form.html, bc/web/templates/little-cases.html, bc/web/urls.py, bc/web/views.py
This provides updated text for a number of pages, and tweaks a few little things here and there.
=> Update copy for a number of pages

bc/core/utils/status/base.py
This PR updates the description in the base template to add square brackets and a line break.
Here's a tweet that uses this new template:
https://twitter.com/flp_tests/status/1640757058994593793
=> feat(core): Tweak the description in the base template

bc/web/urls.py
This PR adds logic to redirect users to the `/big-cases/sponsors/` page when they try to use the `/sponsors/` URL.
=> feat(web): Redirect requests made to the /sponsors URL.

bc/assets/templates/404.html
This PR adds a custom 404 page and fixes https://github.com/freelawproject/bigcases2/issues/182. Here's a screenshot of the page:
=> feat(templates): Add a custom 404 page

bc/subscription/apps.py, bc/subscription/signals.py
This PR adds logic to Invalidate the file from edge caches after adding a new case to the DB. This PR fixes #187.
=> feat(subscription): Invalidate cache after adding a new case.

bc/core/utils/status/templates.py
This PR adds hashtags to the Twitter templates.
=> feat(core): Add hashtag to the twitter templates

.github/dependabot.yml
This PR tweaks the `dependabot.yml` file to group version updates by dependency name.
=> chore(deps): configure Dependabot to create grouped updates

.github/workflows/build-dev.yml, .github/workflows/bulid-and-deploy.yml
See also: freelawproject/courtlistener#2808
=> feat(ci): This should fix deploys for non-members

bc/settings/django.py
This PR fixes the `InvalidStorageError` exception
=> fix(settings): Tweak the staticfiles backend import path

bc/subscription/templates/includes/search_htmx/case-form.html
This PR removes the inline JS code from the case-from template and fixes #323.
=> refactor(subscription): Remove inline JS code from the case-form.html

bc/web/templates/big-cases/sponsors.html
This adds a basic example button leading to Twitter:
=> feat(html): Add an example button

.dockerignore
=> Include scripts in build

README.md, bc/assets/templates/includes/footer.html, bc/assets/templates/includes/header.html, bc/web/templates/homepage.html
This PR updates the donate link to use the new Neon forms.
=> refactor(templates): Update donate links in templates

bc/subscription/utils/courtlistener.py
This PR fixes #446 by implementing the suggested workaround.
=> fix(subscription): Update the lookup_initial_complaint method

bc/assets/templates/includes/header.html, bc/web/templates/big-cases/about.html, bc/web/templates/homepage.html
=> fix(templates): Update links to the Bluesky account

bc/assets/templates/includes/footer.html, bc/channel/utils/connectors/bluesky_api/client.py, bc/subscription/api_views.py, bc/subscription/tasks.py
This PR updates the newsletter link in the footer template and also tweaks the style of the code to fix the issues reported by Black.
=> fix(footer): Updates the newsletter link

bc/web/templates/big-cases/sponsors.html
This updates the sponsorship page to make it more formal. I'm hopeful this will get people to pay for the bot.
=> Update the sponsorship page

poetry.lock, pyproject.toml
This PR fixes the `UnicodeEncodeError` exception in emails by pinning the Django version.
=> fix(emails): Pins the Django version to avoid the  exception

ARCHITECTURE.md, README.md
- Updated/added the correct bot links.
- Add a step to the dev instructions that I had to figure out on my own.
- A few verbiage tweaks where they made sense.
=> Tweak some docs links verbiage

.pre-commit-config.yaml, bc/core/utils/images.py, bc/settings/project/security.py, mypy.ini, pyproject.toml
=> feat(mypy): Add mypy to pre-commit

bc/subscription/tasks.py, bc/subscription/tests/test_tasks.py
This PR enhances the codebase by removing redundant logic introduced in #579 to handle tasks involving documents stored as bytes. Additionally, it renames some variables to align with the new approach.
=> feat(subscription): Removes logic to handle document as bytes objects

bc/assets/templates/includes/header.html
=> feat(header): add Giving Tuesday banner
